# Setup
title:        玉龙智慧学习平台-文档
tagline:      copyright &copy; 合肥市第七中学高一二十三班丁励治
baseurl:      "/jude"
paginate:     1
locale:       "zh"
# About/contact
author:
  name:       合肥市第七中学高一二十三班丁励治
  url:        https://gitee.com/dinglz

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown